### ISSUE TITLE
Differences between this and other MIDI bridges?

### ISSUE THREAD

**Issue by mxmilkiib** [free-creations/a_j_midi#1]
Could it be possible to have a note about the differences between this and other MIDI bridges? Thanks!

**Comment by Harald-LB** [comment]
OK this is still in "status nascendi". Especially the documentation. Which as usual will come last :-)

This shall be more or less a functional clone of `a2jmidi_bridge.c` (see <https://github.com/linuxaudio/a2jmidid>).
Unlike the a2jmidi_bridge it shall:
1. Show a precise timing to the micro second 
2. Gracefully survive system-hibernation
3. Automatically connect to a named USB Midi port when it becomes available.
4. Automatically disconnect the USB Midi port when it is plugged off.

**Comment by Harald-LB** [comment]
Improve readme.md

**Comment by free-creations** [comment]
readme.md now written.
